source 'https://ruby.taobao.org'

gem 'png'
gem 'rmagick'
gem 'nmatrix', '>= 0.2.1'
gem 'rspec'
gem 'rake'
gem 'rake-compiler'
gem 'resque'
gem 'redis-namespace'
gem 'sidekiq'
#gem 'facets'
#gem 'ruby-prof'