position:         [0, 0, 0]
up:               [0, 0, 1]
front:            [1, 0, 0]

retina_width:     0.016   # for human-beings, ~24mm
retina_height:    0.009
aperture_radius:  0.0001  # for human-beings, 3mm ~ 4mm
image_distance:   0.04    # for human-beings, ~3cm
focal_distance:   0.050   # for human-beings, 50mm

width:            192
height:           108

trace_depth:      8