
max_distance:   100
ambient_light:  [0.01, 0.01, 0.01]


lights:
  -
    type:               Spot
    properties:
      name:             Main
      position:         [0, 1, 5]
      radius:           0.8
      color:            [1, 1, 1]
      high_light_rate:  1
      high_light_angle: 3

world_objects:
  -
    type:                         Plane
    properties:
      name:                       ground
      point:                      [0, 0, -1]
      front:                      [0, 0, 1]
      up:                         [1, 0, 0]
      diffuse_rate:               [0.6, 0.6, 0.6]
      reflective_attenuation:     [0.2, 0.2, 0.2]
      ambient:                    [0.01, 0.01, 0.01]
      texture_file_path:          ./textures/floor.jpg
      texture_horizontal_scale:   0.01
      texture_vertical_scale:     0.06
  -
    type:                         Plane
    properties:
      name:                       front wall
      point:                      [30, 0, 0]
      front:                      [-1, 0, 0]
      up:                         [0, 1, 0]
      diffuse_rate:               [0, 0, 0]
      reflective_attenuation:     [0.8, 0.8, 0.8]
      ambient:                    [0.01, 0.01, 0.01]
  -
    type:                         Sphere
    properties:
      name:                       big sphere
      center:                     [8, 1.5, -0.5]
      north_pole:                 [8, 1.5, 0]
      greenwich:                  [7.5, 1.5, -0.5]
      radius:                     0.5
      refractive_rate:            1.1
      reflective_attenuation:     [0.6, 0.6, 0.6]
      refractive_attenuation:     [0, 0, 0]
      diffuse_rate:               [0.3, 0.3, 0.3]
      ambient:                    [0.01, 0.01, 0.01]

  -
    type:                         Sphere
    properties:
      name:                       small sphere
      center:                     [7, -1.3, 0]
#      north_pole:                 [7, -1.5, 0.6]
#      greenwich:                  [6.2, -1.5, -0.2]
      radius:                     0.6
      refractive_rate:            1.6
      reflective_attenuation:     [0, 0, 0]
      refractive_attenuation:     [0.8, 0.8, 0.8]
      diffuse_rate:               [0.1, 0.1, 0.1]
      ambient:                    [0.01, 0.01, 0.01]

