
max_distance:   100
ambient_light:  [0.02, 0.02, 0.02]


lights:
  -
    type:               Spot
    properties:
      name:             Main
      position:         [5, 2, 10]
      radius:           0.01
      color:            [0.6, 0.6, 0.6]
      diffusion_rate:   0.3
      high_light_rate:  1
      high_light_angle: 10

world_objects:
  -
    type:                         Sphere
    properties:
      name:                       big sphere
      center:                     [4, 0, 0]
      radius:                     0.5
      refractive_rate:            1.5
      reflective_attenuation:     [0.5, 0.5, 0.5]
  -
    type:                         Sphere
    properties:
      name:                       small sphere
      center:                     [3, 2, 0]
      radius:                     0.4
      refractive_rate:            1.5
      reflective_attenuation:     [0.5, 0.5, 0.5]