
max_distance:   100
ambient_light:  [0.01, 0.01, 0.01]


lights:
  -
    type:               Spot
    properties:
      name:             Main
      position:         [3, 3, 3]
      radius:           0.04
      color:            [1, 1, 1]
      high_light_rate:  1
      high_light_angle: 3

world_objects:
  -
    type:                         Plane
    properties:
      name:                       ground
      point:                      [0, 0, -4]
      front:                      [0, 0, 1]
      diffuse_rate:               [0.8, 0.8, 0]
      texture:                    grids
#  -
#    type:                         Plane
#    properties:
#      name:                       sky
#      point:                      [0, 0, 4]
#      front:                      [0, 0, -1]
#      diffuse_rate:               [1, 0, 1]
#      texture:                    none
#  -
#    type:                         Plane
#    properties:
#      name:                       right wall
#      point:                      [0, -10, 0]
#      front:                      [0, 1, 0]
#      diffuse_rate:               [1, 1, 1]
#      texture:                    none
#  -
#    type:                         Plane
#    properties:
#      name:                       left wall
#      point:                      [0, 10, 0]
#      front:                      [0, -1, 0]
#      diffuse_rate:               [1, 1, 1]
#      texture:                    none
  -
    type:                         Plane
    properties:
      name:                       front wall
      point:                      [50, 0, 0]
      front:                      [-1, 0, 0]
      diffuse_rate:               [0, 0.7, 1]
      texture:                    none
#  -
#    type:                         Plane
#    properties:
#      name:                       back wall
#      point:                      [-5, 0, 0]
#      front:                      [1, 0, 0]
#      diffuse_rate:               [0, 0, 1]
#      texture:                    none
  -
    type:                         Sphere
    properties:
      name:                       big sphere
      center:                     [6, 1, -0.8]
      north_pole:                 [6, 1, -0.3]
      greenwich:                  [5.5, 1, -0.8]
      radius:                     0.5
      refractive_rate:            1.1
      reflective_attenuation:     [0.1, 0.1, 0.1]
      refractive_attenuation:     [0.8, 0.8, 0]
      diffuse_rate:               [0.7, 0.7, 0.7]

  -
    type:                         Sphere
    properties:
      name:                       small sphere
      center:                     [8, 0.2, 0.1]
      north_pole:                 [8, 0.2, 0.4]
      greenwich:                  [7.7, 0.2, 0.1]
      radius:                     0.3
      refractive_rate:            1.1
      reflective_attenuation:     [0, 0.8, 0.8]
      refractive_attenuation:     [0.8, 0.8, 0]
      diffuse_rate:               [0.8, 0.8, 0.8]

